### ISSUE TITLE
syntactic sugar for $apply f var$

### ISSUE THREAD

**Issue by filippo** [filippo/sgte#3]
Add some syntactic to apply. E.g.
    $apply upperCase strings.name$
might be written as:
    $string.name:upperCase$

**Comment by gregorej** [comment]
I'd love to have that feature.

**Comment by filippo** [comment]
I'll try to work on it in the weekend or earlier if I can :-)

**Comment by gregorej** [comment]
Great! I was also thinking about having additional parameters for these functions, like:

`````` $user.name:default("empty")$```
In this case the ```default/2``` function would take user's name as first argument and string as the second. Does this sound reasonable?
``````

**Comment by filippo** [comment]
It's a good idea, but I think the second element should be another attribute to be passed when rendering the template.
Otherwise you have to distinguish all the various data types and there coud be problems identifying atoms from attributes.
