### ISSUE TITLE
add docs to the wiki

### ISSUE THREAD

**Issue by filippo** [filippo/sgte#5]
Add docs to the wiki

**Comment by tempire** [comment]
Are there any docs for sgte, anywhere?

**Comment by filippo** [comment]
running 
$ make docs
generates the documentation under doc/

**Comment by filippo** [comment]
I added the overview page to the github wiki:
https://github.com/filippo/sgte/wiki/sgte-overview

Also you might take a look at the tests under test/src/
They should be pretty easy to follow.

Fell free to ask you have any problems.
